# Generated by Django 2.1.5 on 2019-04-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wettkaempfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ort', models.CharField(max_length=250)),
                ('Datum', models.DateTimeField(default=None)),
            ],
        ),
    ]
