# Generated by Django 2.1.5 on 2019-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190414_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wettkampf',
            name='Datum',
            field=models.DateField(default=None),
        ),
    ]
