# Generated by Django 2.1.5 on 2019-04-15 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190415_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wettkampf',
            name='Datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
