# Generated by Django 2.1.5 on 2019-04-15 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190415_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wettkampf',
            name='Datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
